spring.application.name=ZenTech

# ================== DATABASE ==================
spring.datasource.url=jdbc:mysql://localhost:3306/ZenTech
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ================== JWT ==================
app.JWT_ACCESS_KEY=${APP_JWT_ACCESS_KEY:hC7duY7FzG2sw8B3eiK5jv9T4rl0A3qp2M1os6R9t4V3}
app.JWT_REFRESH_KEY=${APP_JWT_REFRESH_KEY:X9zK2mN5pQ8rT1wV4yZ7bC0dE3fG6hI9jL2oM5nPkR8s}
app.JWT_ACCESS_ExpirationMs=900000
app.JWT_REFRESH_ExpirationMs=604800000

# Mapping l?i cho ?úng v?i code ?ang dùng
application.security.jwt.secret-key=${app.JWT_ACCESS_KEY}
application.security.jwt.expiration=${app.JWT_ACCESS_ExpirationMs}
application.security.jwt.refresh-expiration=${app.JWT_REFRESH_ExpirationMs}

# ================== GOOGLE OAUTH2 ==================
app.google.client.id=${APP_GOOGLE_CLIENT_ID:172722848021-38o0a01f8t8lhpug43i6fa93f4c4daau.apps.googleusercontent.com}

# ================== MAIL ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:lucthoitrong@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:smpuihbaidahxuey}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ================== CORS ==================
app.cors.allowed-origins=${APP_CORS_ORIGINS:http://localhost:4200}

# ================== Cloudflare ==================
cloudflare.r2.bucket=zentech-media
cloudflare.r2.endpoint=https://8073f086816196c840b804159df23b56.r2.cloudflarestorage.com
cloudflare.r2.access-key=f0750c904ddc0ce0caca19a796cb62b9
cloudflare.r2.secret-key=ef32d5d1b16bbe3b4a85f3ea423ce758b7df44124461bbf58d53d4c2675fc477

# Thoi gian hien tai cua link
cloudflare.r2.presigned-url-expiration=15